/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.3.21"
    kotlin("plugin.serialization") version "2.3.21"
    id("com.gradleup.shadow") version "9.5.1"
    application
}

group = "com.chandu4221.androidcompat"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    gradlePluginPortal()
    // Add the official Gradle repository
    maven {
        url = uri("https://repo.gradle.org/gradle/libs-releases/")
    }
}

dependencies {
    // Gradle Tooling API
    implementation("org.gradle:gradle-tooling-api:8.13") // Pin to latest stable

    // SLF4J no-op to suppress Tooling API logging
    runtimeOnly("org.slf4j:slf4j-nop:2.0.16")

    // Kotlinx serialization for JSON output
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")

    // Kotlin stdlib (bundled by shadow)
    implementation(kotlin("stdlib"))
}

testing {
    suites {
        // Configure the built-in test suite
        val test = named<JvmTestSuite>("test") {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "MainKt"
}

tasks.shadowJar {
    archiveBaseName.set("gradle-bridge")
    archiveClassifier.set("")
    archiveVersion.set("")
    mergeServiceFiles()
}
